### ISSUE TITLE
configure a test server

### ISSUE THREAD

**Issue by odaepo** [TahaMalas/internet_speed_test#1]
It may be helpful to be able to set up and configure the server test.

**Comment by TahaMalas** [comment]
Thanks for your suggestion and suggesting new features to the package

I will start working on it ASAP and hope to be implemented in the next couple of days

Hope this package is making your flutter development process easier

Cheers.

**Comment by TahaMalas** [comment]
Configuring your test server is now implemented in the latest version

`internet_speed_test: ^1.1.0`

Hope it fits your needs and works as expected.

Thanks again for sharing your thoughts with us!
Cheers.
